# Generated by Django 2.0 on 2018-01-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bought',
            field=models.BooleanField(default=False),
        ),
    ]
